theme: jekyll-theme-cayman
title: [K0sasp - hacking with macOS]
description: [Ouh Yeah!]
show_downloads: [true]
github:
  zip_url: https://github.com/kontrol0/K0SASP/archive/1.4.zip
  tar_url: https://github.com/kontrol0/K0SASP/archive/1.4.tar.gz
  another_url: https://github.com/kontrol0/K0SASP/releases

