theme: jekyll-theme-cayman
title: [K0sasp - Hacking with macOS]
show_downloads: [true]
github:
  zip_url: https://github.com/kontrol0/K0SASP/archive/1.4.zip
  another_url: https://github.com/kontrol0/K0SASP/releases

